version: "4.0"
services:
  pg_database:
    image: postgres
    hostname: pg_database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_database
    volumes:
      - /tmp/docker/pg_database:/tmp/pg_database
